CREATE TABLE ACCOUNTS (
   ACCOUNT_NUMBER CHAR(17) PRIMARY KEY,
   NAME TEXT,
   BANK_CODE INT,
   CURRENCY TEXT,
   TRANSPARENT BOOL,
   BALLANCE FLOAT
);

CREATE TABLE TRANSACTIONS(
   ID INTEGER PRIMARY KEY     AUTOINCREMENT,
   SENDER CHAR(17)  NOT NULL,
   RECEIVER CHAR(17)  NOT NULL,
   AMOUNT INT,
   DUE_DATE TEXT,
   CURRENCY TEXT,

   --FOREIGN KEY(SENDER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
   --FOREIGN KEY(RECEIVER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
   UNIQUE(SENDER, RECEIVER, AMOUNT, DUE_DATE, CURRENCY) ON CONFLICT IGNORE
);