CREATE TABLE ACCOUNTS (
   ID INT PRIMARY KEY     NOT NULL,
   ACCOUNT_NUMBER CHAR(17) NOT NULL,
   NAME TEXT,
   BANK_CODE INT,
   CURRENCY TEXT
);

CREATE TABLE TRANSACTIONS(
   ID INT PRIMARY KEY     NOT NULL,
   ACCOUNT_ID INT NOT NULL,
   NAME TEXT,
   BANK_CODE INT,
   FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID)
);